// This file is AUTO-GENERATED by codegen/generate.ts
// Do not edit manually – re-run the generator instead.
//
// npx ts-node codegen/generate.ts --schema forum.json --output _generated.ts --class ForumAPI

import { ApiMixin } from "../core/mixin";

export class ForumAPI extends ApiMixin {

  /** Get Access Token */
  OAuth_Token(): Promise<Response> {
    return this._request("POST", "/oauth/token");
  }

  /** Get CSS */
  Assets_Css(params: { css?: string[] } = {}): Promise<Response> {
    return this._request("GET", "/css", { params });
  }

  /** Get Categories */
  Categories_List(params: { parentCategoryId?: number; parentForumId?: number; order?: string } = {}): Promise<Response> {
    return this._request("GET", "/categories", { params });
  }

  /** Get Category */
  Categories_Get(params: { categoryId: number }): Promise<Response> {
    return this._request("GET", `/categories/${params.categoryId}`);
  }

  /** Get Forums */
  Forums_List(params: { parentCategoryId?: number; parentForumId?: number; order?: string } = {}): Promise<Response> {
    return this._request("GET", "/forums", { params });
  }

  /** Get Forums Tree */
  Forums_Grouped(): Promise<Response> {
    return this._request("GET", "/forums/grouped");
  }

  /** Get Forum */
  Forums_Get(params: { forumId: number }): Promise<Response> {
    return this._request("GET", `/forums/${params.forumId}`);
  }

  /** Get Followers */
  Forums_Followers(params: { forumId: number }): Promise<Response> {
    return this._request("GET", `/forums/${params.forumId}/followers`);
  }

  /** Follow Forum */
  Forums_Follow(params: { forumId: number; post?: boolean; alert?: boolean; email?: boolean; prefixIds?: number[]; minimalContestAmount?: number }): Promise<Response> {
    const { forumId, ...body } = params;
    return this._request("POST", `/forums/${params.forumId}/followers`, { json: body });
  }

  /** Unfollow Forum */
  Forums_Unfollow(params: { forumId: number }): Promise<Response> {
    return this._request("DELETE", `/forums/${params.forumId}/followers`);
  }

  /** Get Followed Forums */
  Forums_Followed(params: { total?: boolean } = {}): Promise<Response> {
    return this._request("GET", "/forums/followed", { params });
  }

  /** Get Feed Options */
  Forums_GetFeedOptions(): Promise<Response> {
    return this._request("GET", "/forums/feed/options");
  }

  /** Edit Feed Options */
  Forums_EditFeedOptions(params: { nodeIds?: number[]; keywords?: string[] } = {}): Promise<Response> {
    return this._request("PUT", "/forums/feed/options", { json: params });
  }

  /** Get Links Forum */
  Links_List(): Promise<Response> {
    return this._request("GET", "/link-forums");
  }

  /** Get Link Forum */
  Links_Get(params: { linkId: number }): Promise<Response> {
    return this._request("GET", `/link-forums/${params.linkId}`);
  }

  /** Get Pages */
  Pages_List(params: { parentPageId?: number; order?: string } = {}): Promise<Response> {
    return this._request("GET", "/pages", { params });
  }

  /** Get Page */
  Pages_Get(params: { pageId: number }): Promise<Response> {
    return this._request("GET", `/pages/${params.pageId}`);
  }

  /** Get Navigation */
  Navigation_List(params: { parent?: number } = {}): Promise<Response> {
    return this._request("GET", "/navigation", { params });
  }

  /** Get Threads */
  Threads_List(params: { forumId?: number; tab?: string; state?: string; period?: string; title?: string; titleOnly?: boolean; creatorUserId?: number; sticky?: boolean; prefixIds__?: number[]; prefixIdsNot__?: number[]; threadTagId?: number; page?: number; limit?: number; order?: string; direction?: string; threadCreateDate?: number; threadUpdateDate?: number; fieldsInclude?: string[] } = {}): Promise<Response> {
    return this._request("GET", "/threads", { params });
  }

  /** Create Thread */
  Threads_Create(params: { postBody: string; forumId: number; title?: string; titleEn?: string; prefixId?: number[]; tags?: string[]; hideContacts?: boolean; allowAskHiddenContent?: boolean; replyGroup?: number; commentIgnoreGroup?: boolean; dontAlertFollowers?: boolean; scheduleDate?: string; scheduleTime?: string; watchThreadState?: boolean; watchThread?: boolean; watchThreadEmail?: boolean }): Promise<Response> {
    return this._request("POST", "/threads", { json: params });
  }

  /** Create Contest */
  Threads_CreateContest(params: { postBody: string; contestType: string; prizeType: string; requireLikeCount: number; requireTotalLikeCount: number; title?: string; titleEn?: string; lengthValue?: number; lengthOption?: string; countWinners?: number; prizeDataMoney?: number; isMoneyPlaces?: boolean; prizeDataPlaces?: number[]; prizeDataUpgrade?: number; secretAnswer?: string; tags?: string[]; replyGroup?: number; commentIgnoreGroup?: boolean; dontAlertFollowers?: boolean; hideContacts?: boolean; allowAskHiddenContent?: boolean; scheduleDate?: string; scheduleTime?: string; watchThreadState?: boolean; watchThread?: boolean; watchThreadEmail?: boolean }): Promise<Response> {
    return this._request("POST", "/contests", { json: params });
  }

  /** Create Claim */
  Threads_Claim(params: { asResponder: string; asIsMarketDeal: boolean; asAmount: number; transferType: string; postBody: string; asMarketItemId?: number; asData?: string; currency?: string; payClaim?: string; asFundsReceipt?: string; asTgLoginScreenshot?: string; tags?: string[]; hideContacts?: boolean; allowAskHiddenContent?: boolean; replyGroup?: number; commentIgnoreGroup?: boolean; dontAlertFollowers?: boolean; scheduleDate?: string; scheduleTime?: string; watchThreadState?: boolean; watchThread?: boolean; watchThreadEmail?: boolean }): Promise<Response> {
    return this._request("POST", "/claims", { json: params });
  }

  /** Get Thread */
  Threads_Get(params: { threadId: number; fieldsInclude?: string[] }): Promise<Response> {
    const { threadId, ...query } = params;
    return this._request("GET", `/threads/${params.threadId}`, { params: query });
  }

  /** Edit thread */
  Threads_Edit(params: { threadId: number; title?: string; titleEn?: string; prefixId?: number[]; tags?: string[]; discussionOpen?: boolean; hideContacts?: boolean; allowAskHiddenContent?: boolean; replyGroup?: number; commentIgnoreGroup?: boolean }): Promise<Response> {
    const { threadId, ...body } = params;
    return this._request("PUT", `/threads/${params.threadId}`, { json: body });
  }

  /** Delete Thread */
  Threads_Delete(params: { threadId: number; reason?: string }): Promise<Response> {
    const { threadId, ...body } = params;
    return this._request("DELETE", `/threads/${params.threadId}`, { json: body });
  }

  /** Move Thread */
  Threads_Move(params: { threadId: number; nodeId: string; title?: string; titleEn?: string; prefixId?: number[]; applyThreadPrefix?: boolean; sendAlert?: boolean }): Promise<Response> {
    const { threadId, ...body } = params;
    return this._request("POST", `/threads/${params.threadId}/move`, { json: body });
  }

  /** Bump Thread */
  Threads_Bump(params: { threadId: number }): Promise<Response> {
    return this._request("POST", `/threads/${params.threadId}/bump`);
  }

  /** Hide Thread */
  Threads_Hide(params: { threadId: number }): Promise<Response> {
    return this._request("POST", `/threads/${params.threadId}/hide`);
  }

  /** Bookmark Thread */
  Threads_Star(params: { threadId: number }): Promise<Response> {
    return this._request("POST", `/threads/${params.threadId}/star`);
  }

  /** Unbookmark Thread */
  Threads_Unstar(params: { threadId: number }): Promise<Response> {
    return this._request("DELETE", `/threads/${params.threadId}/star`);
  }

  /** Get Thread Followers */
  Threads_Followers(params: { threadId: number }): Promise<Response> {
    return this._request("GET", `/threads/${params.threadId}/followers`);
  }

  /** Follow Thread */
  Threads_Follow(params: { threadId: number; email?: boolean }): Promise<Response> {
    const { threadId, ...body } = params;
    return this._request("POST", `/threads/${params.threadId}/followers`, { json: body });
  }

  /** Unfollow Thread */
  Threads_Unfollow(params: { threadId: number }): Promise<Response> {
    return this._request("DELETE", `/threads/${params.threadId}/followers`);
  }

  /** Get Followed Threads */
  Threads_Followed(params: { total?: boolean; fieldsInclude?: string[] } = {}): Promise<Response> {
    return this._request("GET", "/threads/followed", { params });
  }

  /** Get Navigation Elements */
  Threads_Navigation(params: { threadId: number }): Promise<Response> {
    return this._request("GET", `/threads/${params.threadId}/navigation`);
  }

  /** Get Poll */
  Threads_Poll_Get(params: { threadId: number }): Promise<Response> {
    return this._request("GET", `/threads/${params.threadId}/poll`);
  }

  /** Vote Poll */
  Threads_Poll_Vote(params: { threadId: number; responseId?: number; responseIds?: number[] }): Promise<Response> {
    const { threadId, ...body } = params;
    return this._request("POST", `/threads/${params.threadId}/poll/votes`, { json: body });
  }

  /** Get Unread Threads */
  Threads_Unread(params: { limit?: number; forumId?: number; dataLimit?: number } = {}): Promise<Response> {
    return this._request("GET", "/threads/new", { params });
  }

  /** Get Recent Threads */
  Threads_Recent(params: { days?: number; limit?: number; forumId?: number; dataLimit?: number } = {}): Promise<Response> {
    return this._request("GET", "/threads/recent", { params });
  }

  /** Finish Contest */
  Threads_Finish(params: { threadId: number }): Promise<Response> {
    return this._request("POST", `/contests/${params.threadId}/finish`);
  }

  /** Get Posts */
  Posts_List(params: { threadId?: number; pageOfPostId?: number; page?: number; limit?: number; order?: string } = {}): Promise<Response> {
    return this._request("GET", "/posts", { params });
  }

  /** Create Post */
  Posts_Create(params: { postBody: string; threadId?: number; quotePostId?: number }): Promise<Response> {
    return this._request("POST", "/posts", { json: params });
  }

  /** Get Post */
  Posts_Get(params: { postId: number }): Promise<Response> {
    return this._request("GET", `/posts/${params.postId}`);
  }

  /** Edit Post */
  Posts_Edit(params: { postId: number; postBody?: string }): Promise<Response> {
    const { postId, ...body } = params;
    return this._request("PUT", `/posts/${params.postId}`, { json: body });
  }

  /** Delete Post */
  Posts_Delete(params: { postId: number; reason?: string }): Promise<Response> {
    const { postId, ...body } = params;
    return this._request("DELETE", `/posts/${params.postId}`, { json: body });
  }

  /** Get Post Likes */
  Posts_Likes(params: { postId: number; page?: number; limit?: number }): Promise<Response> {
    const { postId, ...query } = params;
    return this._request("GET", `/posts/${params.postId}/likes`, { params: query });
  }

  /** Like Post */
  Posts_Like(params: { postId: number }): Promise<Response> {
    return this._request("POST", `/posts/${params.postId}/likes`);
  }

  /** Unlike Post */
  Posts_Unlike(params: { postId: number }): Promise<Response> {
    return this._request("DELETE", `/posts/${params.postId}/likes`);
  }

  /** Get Post Report Reasons */
  Posts_ReportReasons(params: { postId: number }): Promise<Response> {
    return this._request("GET", `/posts/${params.postId}/report`);
  }

  /** Report Post */
  Posts_Report(params: { postId: number; message: string }): Promise<Response> {
    const { postId, ...body } = params;
    return this._request("POST", `/posts/${params.postId}/report`, { json: body });
  }

  /** Get Post Comments */
  Posts_Comments_Get(params: { postId: number; before?: number; beforeComment?: number }): Promise<Response> {
    return this._request("GET", "/posts/comments", { params });
  }

  /** Create Post Comment */
  Posts_Comments_Create(params: { postId: number; commentBody: string }): Promise<Response> {
    return this._request("POST", "/posts/comments", { json: params });
  }

  /** Edit Post Comment */
  Posts_Comments_Edit(params: { postCommentId: number; commentBody: string }): Promise<Response> {
    return this._request("PUT", "/posts/comments", { json: params });
  }

  /** Delete Post Comment */
  Posts_Comments_Delete(params: { postCommentId: number; reason?: string }): Promise<Response> {
    return this._request("DELETE", "/posts/comments", { json: params });
  }

  /** Report Post Comment */
  Posts_Comments_Report(params: { postCommentId: number; message: string }): Promise<Response> {
    return this._request("POST", "/posts/comments/report", { json: params });
  }

  /** Get Users */
  Users_List(params: { page?: number; limit?: number; fieldsInclude?: string[] } = {}): Promise<Response> {
    return this._request("GET", "/users", { params });
  }

  /** Get User Fields */
  Users_Fields(): Promise<Response> {
    return this._request("GET", "/users/fields");
  }

  /** Find Users */
  Users_Find(params: { username?: string; customFields?: Record<string, unknown>; fieldsInclude?: string[] } = {}): Promise<Response> {
    return this._request("GET", "/users/find", { params });
  }

  /** Get User */
  Users_Get(params: { userId: unknown; fieldsInclude?: string[] }): Promise<Response> {
    const { userId, ...query } = params;
    return this._request("GET", `/users/${params.userId}`, { params: query });
  }

  /** Edit User */
  Users_Edit(params: { userId: unknown; username?: string; userTitle?: string; displayGroupId?: number; displayIconGroupId?: number; displayBannerId?: number; convWelcomeMessage?: string; userDobDay?: number; userDobMonth?: number; userDobYear?: number; secretAnswer?: string; secretAnswerType?: number; shortLink?: string; languageId?: number; gender?: string; timezone?: string; receiveAdminEmail?: boolean; activityVisible?: boolean; showDobDate?: boolean; showDobYear?: boolean; hideUsernameChangeLogs?: boolean; allowViewProfile?: string; allowPostProfile?: string; allowSendPersonalConversation?: string; allowInviteGroup?: string; allowReceiveNewsFeed?: string; alert?: Record<string, unknown>; fields?: Record<string, unknown> }): Promise<Response> {
    const { userId, ...body } = params;
    return this._request("PUT", `/users/${params.userId}`, { json: body });
  }

  /** Get User Claims */
  Users_Claims(params: { userId: unknown; type_?: string; claimState?: string }): Promise<Response> {
    const { userId, ...query } = params;
    return this._request("GET", `/users/${params.userId}/claims`, { params: query });
  }

  /** Upload Avatar */
  Users_Avatar_Upload(params: { userId: unknown; avatar: string; x?: number; y?: number; crop?: number }): Promise<Response> {
    const { userId, ...body } = params;
    return this._request("POST", `/users/${params.userId}/avatar`, { json: body });
  }

  /** Delete Avatar */
  Users_Avatar_Delete(params: { userId: unknown }): Promise<Response> {
    return this._request("DELETE", `/users/${params.userId}/avatar`);
  }

  /** Crop Avatar */
  Users_Avatar_Crop(params: { userId: unknown; x?: number; y?: number; crop?: number }): Promise<Response> {
    const { userId, ...body } = params;
    return this._request("POST", `/users/${params.userId}/avatar/crop`, { json: body });
  }

  /** Upload Background */
  Users_Background_Upload(params: { userId: unknown; background: string; x?: number; y?: number; crop?: number }): Promise<Response> {
    const { userId, ...body } = params;
    return this._request("POST", `/users/${params.userId}/background`, { json: body });
  }

  /** Delete Background */
  Users_Background_Delete(params: { userId: unknown }): Promise<Response> {
    return this._request("DELETE", `/users/${params.userId}/background`);
  }

  /** Crop Background */
  Users_Background_Crop(params: { userId: unknown; x?: number; y?: number; crop?: number }): Promise<Response> {
    const { userId, ...body } = params;
    return this._request("POST", `/users/${params.userId}/background/crop`, { json: body });
  }

  /** Get User Followers */
  Users_Followers(params: { userId: unknown; order?: string; page?: number; limit?: number }): Promise<Response> {
    const { userId, ...query } = params;
    return this._request("GET", `/users/${params.userId}/followers`, { params: query });
  }

  /** Follow User */
  Users_Follow(params: { userId: unknown }): Promise<Response> {
    return this._request("POST", `/users/${params.userId}/followers`);
  }

  /** Unfollow User */
  Users_Unfollow(params: { userId: unknown }): Promise<Response> {
    return this._request("DELETE", `/users/${params.userId}/followers`);
  }

  /** Get Followed Users By User */
  Users_Followings(params: { userId: unknown; order?: string; page?: number; limit?: number }): Promise<Response> {
    const { userId, ...query } = params;
    return this._request("GET", `/users/${params.userId}/followings`, { params: query });
  }

  /** Get User Likes */
  Users_Likes(params: { userId: unknown; nodeId?: number; likeType?: string; type_?: string; page?: number; contentType?: string; searchUserId?: number; stats?: boolean }): Promise<Response> {
    const { userId, ...query } = params;
    return this._request("GET", `/users/${params.userId}/likes`, { params: query });
  }

  /** Get Ignored Users */
  Users_Ignored(params: { total?: boolean } = {}): Promise<Response> {
    return this._request("GET", "/users/ignored", { params });
  }

  /** Ignore User */
  Users_Ignore(params: { userId: unknown }): Promise<Response> {
    return this._request("POST", `/users/${params.userId}/ignore`);
  }

  /** Edit Ignoring Options */
  Users_IgnoreEdit(params: { userId: unknown; ignoreConversations?: boolean; ignoreContent?: boolean; restrictViewProfile?: boolean }): Promise<Response> {
    const { userId, ...query } = params;
    return this._request("PUT", `/users/${params.userId}/ignore`, { params: query });
  }

  /** Unignore User */
  Users_Unignore(params: { userId: unknown }): Promise<Response> {
    return this._request("DELETE", `/users/${params.userId}/ignore`);
  }

  /** Get Contents */
  Users_Contents(params: { userId: unknown; page?: number; limit?: number }): Promise<Response> {
    const { userId, ...query } = params;
    return this._request("GET", `/users/${params.userId}/timeline`, { params: query });
  }

  /** Get Trophies */
  Users_Trophies(params: { userId: unknown }): Promise<Response> {
    return this._request("GET", `/users/${params.userId}/trophies`);
  }

  /** Get Secret Answer Types */
  Users_SecretAnswerTypes(): Promise<Response> {
    return this._request("GET", "/users/secret-answer/types");
  }

  /** Reset Secret Answer */
  Users_SA_Reset(): Promise<Response> {
    return this._request("POST", "/account/secret-answer/reset");
  }

  /** Cancel Secret Answer Reset */
  Users_SA_CancelReset(): Promise<Response> {
    return this._request("DELETE", "/account/secret-answer/reset");
  }

  /** Get Profile Posts */
  ProfilePosts_List(params: { userId: unknown; postsUserId?: number; page?: number; limit?: number; fieldsInclude?: string[] }): Promise<Response> {
    const { userId, ...query } = params;
    return this._request("GET", `/users/${params.userId}/profile-posts`, { params: query });
  }

  /** Get Profile Post */
  ProfilePosts_Get(params: { profilePostId: number }): Promise<Response> {
    return this._request("GET", `/profile-posts/${params.profilePostId}`);
  }

  /** Edit Profile Post */
  ProfilePosts_Edit(params: { profilePostId: number; postBody?: string; disableComments?: boolean }): Promise<Response> {
    const { profilePostId, ...body } = params;
    return this._request("PUT", `/profile-posts/${params.profilePostId}`, { json: body });
  }

  /** Delete Profile Post */
  ProfilePosts_Delete(params: { profilePostId: number; reason?: string }): Promise<Response> {
    const { profilePostId, ...query } = params;
    return this._request("DELETE", `/profile-posts/${params.profilePostId}`, { params: query });
  }

  /** Get Profile Post Report Reasons */
  ProfilePosts_ReportReasons(params: { profilePostId: number }): Promise<Response> {
    return this._request("GET", `/profile-posts/${params.profilePostId}/report`);
  }

  /** Report a Profile Post */
  ProfilePosts_Report(params: { profilePostId: number; message: string }): Promise<Response> {
    const { profilePostId, ...body } = params;
    return this._request("POST", `/profile-posts/${params.profilePostId}/report`, { json: body });
  }

  /** Create Profile Post */
  ProfilePosts_Create(params: { userId: unknown; postBody: string }): Promise<Response> {
    return this._request("POST", "/profile-posts", { json: params });
  }

  /** Stick Profile Post */
  ProfilePosts_Stick(params: { profilePostId: number }): Promise<Response> {
    return this._request("POST", `/profile-posts/${params.profilePostId}/stick`);
  }

  /** Unstick Profile Post */
  ProfilePosts_Unstick(params: { profilePostId: number }): Promise<Response> {
    return this._request("DELETE", `/profile-posts/${params.profilePostId}/stick`);
  }

  /** Get Profile Post Likes */
  ProfilePosts_Likes(params: { profilePostId: number }): Promise<Response> {
    return this._request("GET", `/profile-posts/${params.profilePostId}/likes`);
  }

  /** Like Profile Post */
  ProfilePosts_Like(params: { profilePostId: number }): Promise<Response> {
    return this._request("POST", `/profile-posts/${params.profilePostId}/likes`);
  }

  /** Unlike Profile Post */
  ProfilePosts_Unlike(params: { profilePostId: number }): Promise<Response> {
    return this._request("DELETE", `/profile-posts/${params.profilePostId}/likes`);
  }

  /** Get Profile Post Comments */
  ProfilePosts_Comments_List(params: { profilePostId: number; before?: number; limit?: number }): Promise<Response> {
    return this._request("GET", "/profile-posts/comments", { params });
  }

  /** Create Profile Post Comment */
  ProfilePosts_Comments_Create(params: { profilePostId: number; commentBody: string }): Promise<Response> {
    return this._request("POST", "/profile-posts/comments", { json: params });
  }

  /** Edit Profile Post Comment */
  ProfilePosts_Comments_Edit(params: { commentId: number; commentBody: string }): Promise<Response> {
    return this._request("PUT", "/profile-posts/comments", { json: params });
  }

  /** Delete Profile Post Comment */
  ProfilePosts_Comments_Delete(params: { commentId: number }): Promise<Response> {
    return this._request("DELETE", "/profile-posts/comments", { json: params });
  }

  /** Get Profile Post Comment */
  ProfilePosts_Comments_Get(params: { profilePostId: number; commentId: number }): Promise<Response> {
    return this._request("GET", `/profile-posts/${params.profilePostId}/comments/${params.commentId}`);
  }

  /** Report a Profile Post Comment */
  ProfilePosts_Comments_Report(params: { commentId: number; message: string }): Promise<Response> {
    const { commentId, ...body } = params;
    return this._request("POST", `/profile-posts/comments/${params.commentId}/report`, { json: body });
  }

  /** Get Conversations */
  Conversations_List(params: { folder?: string; page?: number; limit?: number } = {}): Promise<Response> {
    return this._request("GET", "/conversations", { params });
  }

  /** Create Conversation */
  Conversations_Create(params: { recipientId?: number; recipients?: string[]; isGroup?: boolean; title?: string; openInvite?: boolean; allowEditMessages?: boolean; allowStickyMessages?: boolean; allowDeleteOwnMessages?: boolean; messageBody?: string } = {}): Promise<Response> {
    return this._request("POST", "/conversations", { json: params });
  }

  /** Edit Conversation */
  Conversations_Update(params: { conversationId: number; title?: string; openInvite?: boolean; historyOpen?: boolean; allowEditMessages?: boolean; allowStickyMessages?: boolean; allowDeleteOwnMessages?: boolean }): Promise<Response> {
    return this._request("PUT", "/conversations", { json: params });
  }

  /** Leave Conversation */
  Conversations_Delete(params: { conversationId: number; deleteType: string }): Promise<Response> {
    return this._request("DELETE", "/conversations", { json: params });
  }

  /** Start Conversation */
  Conversations_Start(params: { userId: unknown }): Promise<Response> {
    return this._request("POST", "/conversations/start", { json: params });
  }

  /** Send Content To Saved Messages */
  Conversations_Save(params: { link: string }): Promise<Response> {
    return this._request("POST", "/conversations/save", { json: params });
  }

  /** Get Conversation */
  Conversations_Get(params: { conversationId: number }): Promise<Response> {
    return this._request("GET", `/conversations/${params.conversationId}`);
  }

  /** Get Conversation Messages */
  Conversations_Messages_List(params: { conversationId: number; page?: number; limit?: number; order?: string; before?: number; after?: number }): Promise<Response> {
    const { conversationId, ...query } = params;
    return this._request("GET", `/conversations/${params.conversationId}/messages`, { params: query });
  }

  /** Create Conversation Message */
  Conversations_Messages_Create(params: { conversationId: number; messageBody: string; replyMessageId?: number }): Promise<Response> {
    const { conversationId, ...body } = params;
    return this._request("POST", `/conversations/${params.conversationId}/messages`, { json: body });
  }

  /** Search Conversations Messages */
  Conversations_Search(params: { q?: string; conversationId?: number; searchRecipients?: boolean } = {}): Promise<Response> {
    return this._request("POST", "/conversations/search", { json: params });
  }

  /** Get Conversation Message */
  Conversations_Messages_Get(params: { messageId: number }): Promise<Response> {
    return this._request("GET", `/conversations/messages/${params.messageId}`);
  }

  /** Edit Conversation Message */
  Conversations_Messages_Edit(params: { conversationId: number; messageId: number; messageBody: string }): Promise<Response> {
    const { conversationId, messageId, ...body } = params;
    return this._request("PUT", `/conversations/${params.conversationId}/messages/${params.messageId}`, { json: body });
  }

  /** Delete Conversation Message */
  Conversations_Messages_Delete(params: { conversationId: number; messageId: number }): Promise<Response> {
    return this._request("DELETE", `/conversations/${params.conversationId}/messages/${params.messageId}`);
  }

  /** Invite Users to Conversation */
  Conversations_Invite(params: { conversationId: number; recipients: string[] }): Promise<Response> {
    const { conversationId, ...body } = params;
    return this._request("POST", `/conversations/${params.conversationId}/invite`, { json: body });
  }

  /** Kick User from Conversation */
  Conversations_Kick(params: { conversationId: number; userId: number }): Promise<Response> {
    const { conversationId, ...body } = params;
    return this._request("POST", `/conversations/${params.conversationId}/kick`, { json: body });
  }

  /** Read a Conversation */
  Conversations_Read(params: { conversationId: number }): Promise<Response> {
    return this._request("POST", `/conversations/${params.conversationId}/read`);
  }

  /** Read All Conversations */
  Conversations_ReadAll(): Promise<Response> {
    return this._request("POST", "/conversations/read-all");
  }

  /** Stick Conversation Message */
  Conversations_Messages_Stick(params: { conversationId: number; messageId: number }): Promise<Response> {
    return this._request("POST", `/conversations/${params.conversationId}/messages/${params.messageId}/stick`);
  }

  /** Unstick Conversation Message */
  Conversations_Messages_Unstick(params: { conversationId: number; messageId: number }): Promise<Response> {
    return this._request("DELETE", `/conversations/${params.conversationId}/messages/${params.messageId}/stick`);
  }

  /** Star Conversation */
  Conversations_Star(params: { conversationId: number }): Promise<Response> {
    return this._request("POST", `/conversations/${params.conversationId}/star`);
  }

  /** Unstar Conversation */
  Conversations_Unstar(params: { conversationId: number }): Promise<Response> {
    return this._request("DELETE", `/conversations/${params.conversationId}/star`);
  }

  /** Enable Conversation Alerts */
  Conversations_Alerts_Enable(params: { conversationId: number }): Promise<Response> {
    return this._request("POST", `/conversations/${params.conversationId}/alerts`);
  }

  /** Disable Conversation Alerts */
  Conversations_Alerts_Disable(params: { conversationId: number }): Promise<Response> {
    return this._request("DELETE", `/conversations/${params.conversationId}/alerts`);
  }

  /** Get Notifications */
  Notifications_List(params: { type_?: string; page?: number; limit?: number } = {}): Promise<Response> {
    return this._request("GET", "/notifications", { params });
  }

  /** Get Notification */
  Notifications_Get(params: { notificationId: number }): Promise<Response> {
    return this._request("GET", `/notifications/${params.notificationId}/content`);
  }

  /** Mark Notification Read */
  Notifications_Read(params: { notificationId?: number } = {}): Promise<Response> {
    return this._request("POST", "/notifications/read", { json: params });
  }

  /** Get Popular Tags */
  Tags_Popular(): Promise<Response> {
    return this._request("GET", "/tags");
  }

  /** Get Tags */
  Tags_List(params: { page?: number; limit?: number } = {}): Promise<Response> {
    return this._request("GET", "/tags/list", { params });
  }

  /** Get Tagged Content */
  Tags_Get(params: { tagId: number; page?: number; limit?: number }): Promise<Response> {
    const { tagId, ...query } = params;
    return this._request("GET", `/tags/${params.tagId}`, { params: query });
  }

  /** Get Filtered Content */
  Tags_Find(params: { tag: string }): Promise<Response> {
    return this._request("GET", "/tags/find", { params });
  }

  /** Search */
  Search_All(params: { q?: string; tag?: string; forumId?: number; userId?: unknown; page?: number; limit?: number } = {}): Promise<Response> {
    return this._request("POST", "/search", { json: params });
  }

  /** Search Thread */
  Search_Threads(params: { q?: string; tag?: string; forumId?: number; userId?: unknown; page?: number; limit?: number; dataLimit?: number } = {}): Promise<Response> {
    return this._request("POST", "/search/threads", { json: params });
  }

  /** Search Post */
  Search_Posts(params: { q?: string; tag?: string; forumId?: number; userId?: unknown; page?: number; limit?: number; dataLimit?: number } = {}): Promise<Response> {
    return this._request("POST", "/search/posts", { json: params });
  }

  /** Search Users */
  Search_Users(params: { q?: string } = {}): Promise<Response> {
    return this._request("POST", "/search/users", { json: params });
  }

  /** Search Profile Posts */
  Search_ProfilePosts(params: { q?: string; userId?: number; page?: number; limit?: number } = {}): Promise<Response> {
    return this._request("POST", "/search/profile-posts", { json: params });
  }

  /** Search Tagged */
  Search_Tagged(params: { tag?: string; tags?: string[]; page?: number; limit?: number } = {}): Promise<Response> {
    return this._request("POST", "/search/tagged", { json: params });
  }

  /** Get Search Results */
  Search_Results(params: { searchId: unknown; page?: number; limit?: number }): Promise<Response> {
    const { searchId, ...body } = params;
    return this._request("GET", `/search/${params.searchId}/results`, { json: body });
  }

  /** Batch */
  Batch_Execute(): Promise<Response> {
    return this._request("POST", "/batch");
  }

  /** Get Chats */
  Chatbox_Index(params: { roomId?: unknown } = {}): Promise<Response> {
    return this._request("GET", "/chatbox", { params });
  }

  /** Get Chat Messages */
  Chatbox_GetMessages(params: { roomId: unknown; beforeMessageId?: number }): Promise<Response> {
    return this._request("GET", "/chatbox/messages", { params });
  }

  /** Create Chat Message */
  Chatbox_PostMessage(params: { roomId: unknown; message: string; replyMessageId?: number }): Promise<Response> {
    return this._request("POST", "/chatbox/messages", { json: params });
  }

  /** Edit Chat Message */
  Chatbox_EditMessage(params: { messageId: number; message: string }): Promise<Response> {
    return this._request("PUT", "/chatbox/messages", { json: params });
  }

  /** Delete Chat Message */
  Chatbox_DeleteMessage(params: { messageId: number }): Promise<Response> {
    return this._request("DELETE", "/chatbox/messages", { json: params });
  }

  /** Get Chat Online */
  Chatbox_Online(params: { roomId: unknown }): Promise<Response> {
    return this._request("GET", "/chatbox/messages/online", { params });
  }

  /** Get Chat Message Report Reasons */
  Chatbox_ReportReasons(params: { messageId: number }): Promise<Response> {
    return this._request("GET", "/chatbox/messages/report", { params });
  }

  /** Report Chat Message */
  Chatbox_Report(params: { messageId: number; reason: string }): Promise<Response> {
    return this._request("POST", "/chatbox/messages/report", { json: params });
  }

  /** Get Chat Leaderboard */
  Chatbox_GetLeaderboard(params: { duration?: string } = {}): Promise<Response> {
    return this._request("GET", "/chatbox/messages/leaderboard", { params });
  }

  /** Get Ignored Chat Users */
  Chatbox_GetIgnore(): Promise<Response> {
    return this._request("GET", "/chatbox/ignore");
  }

  /** Ignore Chat User */
  Chatbox_PostIgnore(params: { userId: unknown }): Promise<Response> {
    return this._request("POST", "/chatbox/ignore", { json: params });
  }

  /** Unignore Chat User */
  Chatbox_DeleteIgnore(params: { userId: unknown }): Promise<Response> {
    return this._request("DELETE", "/chatbox/ignore", { json: params });
  }

  /** Get Forms List */
  Forms_List(params: { page?: number } = {}): Promise<Response> {
    return this._request("GET", "/forms", { params });
  }

  /** Create Form */
  Forms_Create(): Promise<Response> {
    return this._request("POST", "/forms/save");
  }

}
